const NUMBER_OF_FAKE_USERS = 1000;
const PAGE_SIZE = 20;
const RATIO_OF_TOTAL_LISTINGS_TO_FETCH = 0.05;
const MIN_LISTINGS_TO_FETCH = 40;
const RATIO_OF_SOLD_LISTINGS = 0.3;

const SIMILARITY_DEPTHS = [
  { YEAR_RANGE: 1, MILEAGE_FACTOR: 0.10 },
  { YEAR_RANGE: 3, MILEAGE_FACTOR: 0.30 },
  { YEAR_RANGE: 0, MILEAGE_FACTOR: 0.00 } // no limit
]
const MINIMUM_COMPS_REQUIRED = 10;

const EARTH_RADIUS_MILES = 3_959;
const RADIANS_PER_DEGREE = Math.PI / 180;

const MS_PER_DAY = 1000 * 60 * 60 * 24;

const MIN_LISTINGS_TO_FACTOR_IN_SELLER_LISTINGS = 3;
const SMOOTHING_K = 3;
const SELLER_FACTOR_MIN = 0.9;
const SELLER_FACTOR_MAX = 1.1;

module.exports = {
  NUMBER_OF_FAKE_USERS,
  PAGE_SIZE,
  RATIO_OF_TOTAL_LISTINGS_TO_FETCH,
  MIN_LISTINGS_TO_FETCH,
  RATIO_OF_SOLD_LISTINGS,
  SIMILARITY_DEPTHS,
  MINIMUM_COMPS_REQUIRED,
  EARTH_RADIUS_MILES,
  RADIANS_PER_DEGREE,
  MS_PER_DAY,
  MIN_LISTINGS_TO_FACTOR_IN_SELLER_LISTINGS,
  SMOOTHING_K,
  SELLER_FACTOR_MIN,
  SELLER_FACTOR_MAX
}