const SIMILARITY_DEPTHS = [
  { YEAR_RANGE: 1, MILEAGE_FACTOR: 0.10 },
  { YEAR_RANGE: 3, MILEAGE_FACTOR: 0.30 },
  { YEAR_RANGE: 0, MILEAGE_FACTOR: 0.00 } // no limit
]
const MINIMUM_COMPS_REQUIRED = 10;

const EARTH_RADIUS_MILES = 3_959;
const RADIANS_PER_DEGREE = Math.PI / 180;

const MS_PER_DAY = 1000 * 60 * 60 * 24;

module.exports = {
  SIMILARITY_DEPTHS,
  MINIMUM_COMPS_REQUIRED,
  EARTH_RADIUS_MILES,
  RADIANS_PER_DEGREE,
  MS_PER_DAY
}